### PR TITLE
Item Types

### PR DESCRIPTION
**Pull request by wfyson**
Just a little bit of extra config for resolving https://github.com/eprintsug/hefce_oa/issues/20

### CODE REVIEW

**Comment by jesusbagpuss** [comment]
Looks good - the only question is (and I blame Tim for this :o) whether we should try and standardise on 'hefce_oa' or 'ref_cc' (or is there a good reason both are in use!?).
e.g.

```
$c->{hefce_oa_item_types}
```

instead of

```
$c->{ref_cc_item_types}
```

**Comment by wfyson** [comment]
Yes I've been wondering about this as well and it does get a bit confusing. I almost always refer to it as REF CC when I'm talking to people about it, but thinking about it that very much seems to be its external name whereas in the code it is usually hefce_oa so we may wish to opt for that.

**Comment by jesusbagpuss** [comment]
Did a bit more digging, `$c->{hefce_oa}->{item_types}` is probably the best!?

**Comment by jesusbagpuss** [comment]
If you're happy with the last commit, I'll merge this PR.

**Comment by wfyson** [comment]
Looks good to me! Thanks!

**Pull request merged**
