### PR TITLE
Automatic population of embargo length.

### PR DESCRIPTION
**Pull request by wfyson**
Fix for https://github.com/eprintsug/hefce_oa/issues/23

Will try and use the published online date where possible and then the published date as per HEFCE guidance (although should it actually compare them and use the earliest rather than assume published_online will be the earliest?).

### CODE REVIEW

**Comment by wfyson** [comment]
So I've added a new function for getting the earliest embargo date that is available.... But is this actually quite what we need, as presumably this may not always relate to a document that corresponds to the publication date...?

**Comment by jesusbagpuss** [comment]
You're right - that's what I meant with 'get AAMs and VoRs' - the two document content types we're interested in for compliance measuring.
e.g.
Doc1: content: published; embargo: 2020-01-01
Doc2: content: accepted; embargo: 2016-07-01 
- we should return Doc2 (as it will be compliant) not Doc1 (which will fail).

I think the solution is 1/2 way between what you've got now, and what you had before!

Quick question: are we trying to get this shipped today?
I'm ~80% there with Issue26...

**Comment by wfyson** [comment]
I see now, so we get all of the documents where content is either "published" or "accepted" and then get the earliest embargo date from those?

I don't think its likely I'll be updating the bazaar with the new version of the plugin today, but hopefully we'll be able to do it tomorrow if that's ok?

**Comment by jesusbagpuss** [comment]
Hi, had another thought on this - something 'public' and without an embargo should 'beat' something with an embargo (in the accepted / published version 'best document' calculation).

Having this as an over-ridable $c function becomes really useful here - e.g. I can add a test to make sure items with a 'hidden' security flag don't get returned as a possible match.
If an academic uploads a published file that we can't make available, we normally mark it as 'hidden' rather than getting rid of it (as we may be able to use it in the future). The 'hidden' security option is a local addition - so being able to handle it in the document selection process is really good.

I'm just running up a new version of the icon and then I thing #26 will be ready for a PR.

**Comment by wfyson** [comment]
So just to double check I'm understanding you correctly here, if there is a document that has a content value of either "published" or "accepted" and with no embargo date set, then we essentially don't try and calculate an embargo length at all, even if other documents in the record do have an embargo date?

**Comment by jesusbagpuss** [comment]
This makes my head hurt... but I think I've got it sussed out. Might be worth running this past Justin to see what he reckons too?

Here's a table of what I think the preferences should come out as (a ranking of 1 = most preferred. an 'X' in the ranking means the document isn't a valid option, so isn't considered).

In my head I'm using these questions:
- which versions are we interested in? published > accepted (filter for _only_ these contents)
- which versions are compliant NOW? $doc->is_public (a public doc beats a non-public doc)
- which version will become access-compliant soonest? (a sooner-public doc beats a later-public doc)

| ranking | content | embargo_date | is_public | reasoning |
| --- | --- | --- | --- | --- |
| 1 | published | - | Y | (published, OA Now) > (accepted, OA now) |
| 2 | accepted | - | Y | (accepted, OA now) > (published, embargoed) |
| 3 | accepted | 2016-10-01 | N | (accepted, sooner) > (accepted, later) |
| 4 | accepted | 2017-01-01 | N | (accepted, later) > (published, even-later) |
| 5 | published | 2020-01-01 | N | (will become OA automatically) > (won't be OA automatically) |
| 6 | published | - | N | not public, won't be OA automatically, pub > acc |
| 7 | accepted | - | N | not public, won't be OA automatically |
| X | submitted | - | Y | not a valid content type |
| X | supplemental | - | Y | not a valid content type |

Does that seem logical?
Are there any other valid document options that I've overlooked?
Have I gone completely mad?

**Comment by wfyson** [comment]
I think that seems logical and sound although I may have gone a bit mad myself...

**Comment by wfyson** [comment]
Ok then, I think I have implemented the above... 

In short, I get all the documents and order them with published and accepted ones coming first. We then cycle through them all and if they are published or accepted and have an embargo date set then we set that as the latest result, with any documents that have an earlier embargo beating any that have been previously set. If no embargo date has been set and the document is public we simply return there and then (as published documents are checked before accepted ones) and if no embargo date has been set and it isn't public and it's the first document we've come across we store the document to be returned (unless something better comes along)! 

I'm sure it can probably be implemented far more efficiently than the above but let me know what you think!

**Comment by jesusbagpuss** [comment]
I **think** this is more efficient - and a bit more readable?

I'll try and write a test for this function (that'll make my head hirt even more!).
In commit 702958a there's a couple of commented-out DEBUG blocks you can use to see the affect of the sorting.

**Comment by jesusbagpuss** [comment]
Hmmm, interesting quirk of EPrints:
- doing `$doc->is_set( "security" )` results in a 'non existent field document/security - but it **does** exist...
- doing `$doc->is_set( "date_embargo" )` works OK.

Workaround: `$doc->exists_and_set( "security" )` - but this feels like a possible bug in the underlying EPrints code..?

**Comment by wfyson** [comment]
Hmm, that is a weird bug isn't it - just checked it myself and it happens to me too and I've raised it with the team here and no one seems to know anything about it unfortunately. One to look into another time I think!

Meanwhile, I seem to have some problems with the new commits: namely if I have a published document visible to anyone with no embargo and an accepted document visible to staff only with an embargo, the former document should take precedence, but nevertheless an embargo is being set. Haven't looked into why at the time of writing however so shall do that now...

**Comment by jesusbagpuss** [comment]
Oh, hang on a minute...
Just tried to check what the bug was. I had $doc->is_set( "security " ) - which is a very silly thing to do (and is probably why your sort order wasn't right. Sorry!

**Comment by wfyson** [comment]
So it seems that exists_and_set is not a valid workaround as that's always resolving to 0 and thus the first line of the sort doesn't work. Do we need the exists_and_set at all however...?

**Comment by wfyson** [comment]
Hmm I'm confused now - where did you have $doc->is_set( "security " ) ?

**Comment by jesusbagpuss** [comment]
See: c6ebf33 - and i've just pushed 76ae85c to fix another occurrence.
It was actually a $_->is_set( "security" )...

**Comment by wfyson** [comment]
Ah I see, we had identified the same problematic bit, although I assumed it was a problem with exists_and_set rather than a typo!

**Comment by wfyson** [comment]
I've just added the above quickly as I noticed whilst testing that previous values weren't being overwritten if they became redundant.

Although having now committed it I realise that introduces an dilemma: do we want to keep embargo length populated once the embargo has passed and the embargo date has been erased by eprints? But then if a more relevant document comes along (e.g. a publicly available published document), this should set the embargo length to nothing shouldn't it? 

And do we want to overwrite it with a blank value if the depository knows what the embargo length is but doesn't actually have a document attached to the record yet for whatever reason?

Apologies for adding further confusion...!

**Comment by jesusbagpuss** [comment]
Good question. I think most of the REF_CC stuff 'pins' data at a point in time - so retaining the embargo length will be important.

Possibly, we should use the setting of FOA as a 'lock' for the embargo length.
When we're trying to set the FOA date (as it wasn't set before), we know that something has just been added/released that fulfils the 'ACC_TIMING' test.

``` perl
if( !$eprint->is_set( "hoa_foa" ) ){
    # set emb length
}
```

**Comment by wfyson** [comment]
Hmm, slight problem with that route I think... 'hoa_date_foa' gets set after we try and do the automatic working out of the embargo length. So when the lift embargo script gets executed, the emabrgo date disappears, the document is set public, the embargo length is erased and then hoa_date_foa is set...

**Comment by wfyson** [comment]
Well I think by performing the embargo calculation after we set 'hoa_date_foa' but before we test for compliance the issue is hopefully resolved! Let me know what you think...

**Comment by jesusbagpuss** [comment]
The sort method in select_document breaks when the embargo_date is incomplete.

Do not mrege yet!

**Comment by jesusbagpuss** [comment]
Fixes #23.
Incomplete embargo dates now handled sensibly.

**Pull request merged**
