### PR TITLE
set to compliant if acceptance or published dates is before 1st Apr 2016

### PR DESCRIPTION
**Pull request by cziaarm**
Fix for #45 (or one way to do it anyway)

### CODE REVIEW

**Comment by jesusbagpuss** [comment]
@wfyson - should the eprints branch of this be merged back into here?
Does that cover the aspect the PR resolves?

**Comment by cziaarm** [comment]
@wfyson I like the blue, but would argue to keep the condition for things published before 1st April 2016 too. +1 for @jesusbagpuss suggestion to merge back into eprintsug

**Comment by wfyson** [comment]
Hi @cziaarm @jesusbagpuss 
Thanks for adding the fix! I'm happy to merge the pull request and keep the condition alongside the blue in the reports to help highlight the different rules. However, it is EPrints Services policy to keep all of our contributions in one place now, namely https://github.com/eprints
Therefore I'll merge this over to the eprints fork and then update the Bazaar accordingly.

**Comment by wfyson** [comment]
Hello again @cziaarm @jesusbagpuss 
After merging this I was wondering if it does in fact need a bit of tweaking... Looking back at 1.4 on http://www.hefce.ac.uk/rsrch/oa/FAQ/#general is it the case that only things accepted before April 2016 can simply be regarded as compliant, as opposed to records with an accepted or published date before this time?

Similarly, the test for a First Compliant Deposit being set is still carried out and it'll return 0 if this isn't available, whereas should the test for the date of acceptance being before April 2016 not come before this so that we can instantly sign these things off as being compliant?

(Sorry should have raised these questions before accepting the pull request!)

**Comment by jesusbagpuss** [comment]
My perspective is that these items are not compliant, or uncompliant - they're out-of-scope.

The issue you mention about accept/publish dates above still holds true.

**Comment by jesusbagpuss** [comment]
@wfyson also (hopefully before updating the Bazaar version!):
https://github.com/eprints/hefce_oa/blob/f5d6dbcb3972e4899742d28ddbc0b06f7cb0cec3/cfg/cfg.d/zz_hefce_oa.pl#L86
- the return value from get_state can be undef - leading to a warning in the apache log.

**Comment by wfyson** [comment]
Ah, that raises more possibilities about how to handle this then!

I was thinking on my way home from the office that actually, a First Compliant Deposit does still need to be set as you need to make sure you have something to even think about from a REF perspective, but the point about publication date is probably true like you say.

Ultimately, whilst the items are out of scope, I don't think it does any harm to either treat them like any record with a date of acceptance after April 2016 as it has served the role of getting repository administrators used to dealing with REF compliance, or to mark them all as compliant. Do we know what repository administrators tend to prefer?

**Pull request merged**
